[model]
    name = "ai_tool_embedded_model.pth"

[mysql]
    host = "0.0.0.0"
    port = 3307
    username = "user"
    password = "password"
    db = "mydb"
    tablename = "wp_posts"

[mongodb]
    host = "0.0.0.0"
    port = 27017
    username = "root"
    password = "root"

